### ISSUE TITLE
Application closes

### ISSUE THREAD

**Issue by KilianBZH** [InnoSpectra/ISC-NIRScan-Windows-BLE#1]
Hello,

the application suddenly closes just after capturing

![Capture](https://github.com/user-attachments/assets/13742408-55de-4b6a-af3e-47781f1b2841)

**Comment by JeremyHsieh** [comment]
Your device is not activated. Please check with our sales to get it activated.

**Comment by KilianBZH** [comment]
HEllo,

The device is now activated and the application works.
